<?php

/**
 * PasticcInformatici.Com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@pasticcinformatici.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2017 Skeeller srl (https://www.pasticcinformatici.com)
 *
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$enable = $this->helper('Ciratt\Iubenda\Helper\Data')->getConfig('cookiesolution/general/enable');
$jscode = $this->helper('Ciratt\Iubenda\Helper\Data')->getConfig('cookiesolution/general/jscode');
$nojscode = $this->helper('Ciratt\Iubenda\Helper\Data')->getConfig('cookiesolution/general/nojscode');

if ($enable == 1) {
    if (strip_tags($jscode, '<script>') !== false) {
        echo $jscode;
    } else {
        echo "<script type='text/javascript'>\n";
        echo "alert('" . $nojscode . "');";
        echo "</script>";
    }
}